server:
  port: 8082

spring:
  application:
    name: enrichment-correlation-service
  datasource:
    url: jdbc:sqlite:./data/enrichment.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    com.sdapro: DEBUG
