server:
  port: 8081

spring:
  application:
    name: alert-ingestion-service
  datasource:
    url: jdbc:sqlite:./data/alert-ingestion.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.sdapro: DEBUG
